### PR TITLE
Update common.scad

### PR DESCRIPTION
**Pull request by EricBuijs**
I happened to be working on the same female connector last night. This is my alternative method to design the female connector using a chamfer instead of the polygon function. Just some dummy values were used for the female connector since I didn't know the correct values. 

Drawback of the polygon method is that it's cumbersome to design something simple like a chamfer. This method provides more control. However I do like that you female connector has a conical shape.

Also a simple method to create a fillet was added possibly needed later on. It does Minkowski which renders very slow.

I also printed a couple of modules from Thingiverse and I'm, like you, not to pleased with the connector. They fit only with great trouble and I fear that they easily break.

### CODE REVIEW

**Comment by EricBuijs** [comment]
I've worked on a simple spring earlier which is almost thread. I could make a parametrized version of it and make it fit into the base cylinder.

**Comment by muesli** [comment]
@EricBuijs Just to clarify: I didn't mean to insert a central column with a thread, which would obviously interfere with the larger sensors and PCBs inside the modules, but instead I meant to add a thread on the outside wall of each module, similar to something like this:

threaded box

**Comment by muesli** [comment]
Come to think about it some more, a threaded design would probably introduce some real issues for us:

Modules with enclosures for sensors/PCBs probably would require support to be printed, since the enclosure couldn't start at the bottom layer anymore.

**Comment by EricBuijs** [comment]
What about a bayonet mount: [https://en.wikipedia.org/wiki/Bayonet_mount](https://en.wikipedia.org/wiki/Bayonet_mount)

**Comment by muesli** [comment]
@EricBuijs I'm having a bit of trouble integrating your changes with the existing `base.scad`. Could you try to integrate your changes with @Chaos99 latest work, so we can have a direct comparison?

Fwiw, I also noticed that your solution fixes the OpenSCAD warnings I'm getting and it looks like it may also make OpenSCAD 15.03-3 render without issues (see screenshot of incorrect render in current README).

**Comment by EricBuijs** [comment]
@muesli I'll do that but it will be in the weekend if that's ok (or else hell is breaking loose here at home :D).

**Comment by muesli** [comment]
@EricBuijs A bayonet mount may be an elegant solution indeed, as long as it snaps together tightly and sits snuggly.

I don't think the current connectors are all that bad in reality, though, so it's definitely something we can work with. @Chaos99's connectors are still a bit too small compared with the original design, but I'm sure we'll get there. If we can retain compatibility with existing modules of the old design, that would certainly be nice, but we absolutely don't have to if we got a good enough reason to break it.

**Comment by EricBuijs** [comment]
@muesli 👍 agreed.

**Comment by muesli** [comment]
@EricBuijs Yeah, don't worry. I already appreciate all your contributions and feedback! Also looking forward to what @Chaos99 has to say :-)

**Comment by EricBuijs** [comment]
Given the remarks of @Chaos99 and the progress made on the current master I'm going to close this Pull Request.

**Pull request closed without merging**
