### PR TITLE
scaled connectors

### PR DESCRIPTION
**Pull request by Chaos99**
re-scaled connectors to size of original file

still missing the catch at the end though,
I'm not wiling to pull in a major utilities library just for a 'loft' command supporting multiple shapes along a path to replace the rotary_extrude
To lazy to do it with 'difference' and a bunch of boxes at the moment.

### CODE REVIEW

**Comment by Chaos99** [comment]
This now also includes a workaround for the render errors in OpenSCAD <2018.
Could somebody please test this with an older version and maybe even thingieverse?

**Comment by muesli** [comment]
Awesome work!

I've just ran a test print of this PR's base and can confirm the existing modules fit on top of it and secure to it nicely! The new connectors have a slightly different sized female connector, but that doesn't seem to make much of a difference here.

I'll check the OpenSCAD situation and merge this in with a few local changes I got tonight.

**Comment by muesli** [comment]
@Chaos99 Ok, I noticed one issue reviewing the male connectors in the slicer: the "nose" doesn't start rendering before the second layer. I played with the "-5.7 + 0.45" in common.scad, but I'm not quite sure how you came up with those magic values. Can you elaborate?

**Comment by Chaos99** [comment]
5.7 is the lowest y-value in the polygon definition that makes up the shape for that part. Translating by -5.7 will make it flush with the xy plane. 
The part is scaled so it fits better into the female connector. Applying the scale factor to the size, this corresponds to approx. 0.9mm reduction in height. I move half that height back up to compensate for the lowest point being scaled down too, as the scaling operation works based in the origin, not the center of the object.
This is imprecise, as the lowest point is not exactly half way of the full size. Maybe this is the reason for the missing layer.

**Comment by muesli** [comment]
@Chaos99 Nice!

**Comment by muesli** [comment]
Ok, manually cherry-picked the relevant commits from your branch, since for some reason those two branches diverged rather weirdly. Instead of merge-commits, you could probably use rebasing on your fork to prevent such situations.

**Pull request closed without merging**
